-- =============================================================================
-- DEVELOPMENT SEED ONLY — Enaya company
-- NEW SaaS Development database. Do NOT run against the old ERP project.
-- Do NOT run this in production.
-- =============================================================================
-- Idempotent on slug = 'enaya'. Does not hardcode a company UUID.
-- UUID is generated by the database.
--
-- Run manually in the Supabase SQL editor after the migrations.
-- =============================================================================

insert into public.companies (name, slug, timezone, currency, is_active)
values ('Enaya', 'enaya', 'Africa/Cairo', 'EGP', true)
on conflict (slug) do update
  set name = excluded.name,
      is_active = true,
      deleted_at = null;

-- Confirm the row (UUID is assigned by Postgres, not this file):
-- select id, name, slug, is_active from public.companies where slug = 'enaya';
